version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/

hooks:
  ApplicationStop:
    - location: scripts/httpd_stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/httpd_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/httpd_start.sh
      timeout: 300
      runas: root
