version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/httpd_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/httpd_start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/httpd_stop.sh
      timeout: 300
      runas: root

