version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "deploy-app"
    CONTAINER_NAME: "deploy"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${REPO_URI}:${IMAGE_TAG} .
      - echo Pushing the Docker image...
      - docker push ${REPO_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "${REPO_URI}:${IMAGE_TAG}" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
